name: Pull Request

on:
  push:
    branches:
      - gabrielmarcelino165/*
      - fontegabriel/*
      - alvesoliveirasolucoes/*
      - rafaelmesquitamoura/*
      - tgetnerski/*

jobs:
  run-custom-action:
    needs: terraform
    uses: FIAP-6SOAT-G10/fiap-fast-food-terraform-api-gateway/.github/workflows/pull-request.yaml@main
