name: Pull Request

on:
  push:
    branches:
      - gabrielmarcelino165/*
      - fontegabriel/*
      - alvesoliveirasolucoes/*
      - rafaelmesquitamoura/*
      - tgetnerski/*

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::155224324383:role/LabRole
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

  terraform:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  run-custom-action:
    needs: terraform
    uses: FIAP-6SOAT-G10/fiap-fast-food-terraform-api-gateway/.github/workflows/pull-request.yaml@main
